spring.application.name=App
spring.datasource.url=jdbc:postgresql://localhost:5432/cartservicedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=Asia/Kolkata
logging.level.root=INFO
#logging.level.com.Inventory_Service.App2=DEBUG
server.port=8080

#ct config parts
ct.auth.url=https://auth.us-east-2.aws.commercetools.com/oauth/token
ct.api.url=https://api.us-east-2.aws.commercetools.com
ct.client.id=oi0T0R5A9ae-OTkb1Myn2AZ_
ct.client.secret=iWpctxSq2i3KwR__8GFMQ9h7QAwnGlTq
ct.project.key=ecom-app-123456
