pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Cart Service') {
            steps {
                dir('App') {
                    sh 'chmod +x gradlew'
                    sh './gradlew clean build -x test'
                }
            }
        }

        stage('Test Cart Service') {
            steps {
                dir('App') {
                    sh './gradlew test'
                }
            }
        }

        stage('Package Cart Service') {
            steps {
                dir('App') {
                    sh './gradlew bootJar'
                }
            }
        }
    }

    post {
        success {
            echo 'Cart Service Build Successful!'
        }
        failure {
            echo 'Cart Service Build Failed!'
        }
    }
}